# ./.github/workflows/composer-container.yml

name: Composer php

on: 
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nick-zh/composer-php@master
        with:
          action: 'whereis composer'
