# ./.github/workflows/composer-container.yml
# This is a basic workflow to install composer and test the version

name: Composer install test

# triggered only when a commit is added to the master branch
on: 
 push:
   branches:
     - master

# jobs starting, single job called "composer install"

jobs:
  composer install:
 
# type of runner job will run on
    runs-on: ubuntu-latest

# steps represent a sequence of tasks that are part of the job

    steps:
    # runs a single command using the runners shell
    - name: composer install
      
    # checks out the specific repo w/ custom action
    - uses: nanasess/composer-installer-action@master
    
    # runs install command for composer
    - run: composer install
    
    # checks the version
    - name: check version
    - uses: actions/checkout@v2
    - run: composer -V
