# ./.github/workflows/composer-container.yml

name: Composer php

on: 
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: composer install
    - uses: actions/checkout@master
    - uses: nanasess/composer-installer-action@master
    - run: composer install
      name: check version
    - run: composer -V
