# ./.github/workflows/composer-container.yml
# This is a basic workflow to install composer and test the version

name: Composer install test

# triggered only when a commit is added to the master branch
on: 
 push:
   branches:
     - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs starting, single job called "composer install"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: sudo apt install composer

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Composer should be installed now
        
    # Runs a command to show the composer version installed
    - name: composer version
      run: |
        sudo composer -V
        
    # Testing composer cache
    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
       path: ${{ steps.composer-cache.outputs.dir }}
       key: composer-${{ hashFiles('**/composer.lock') }}
       restore-keys: composer-
